version: '3.9'
services:
  cntnr_ogrencibaksana_nginx:
    image: 'nginx:latest'
    container_name: ogrencibaksana_nginx
    hostname: ogrencibaksana_nginx
    restart: "no"
    depends_on:
      - cntnr_ogrencibaksana_php
    links:
      - cntnr_ogrencibaksana_php
    ports:
      - '8840:80'
    volumes:
      - '../projects:/var/www/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
  cntnr_ogrencibaksana_php:
    build: php
    container_name: ogrencibaksana_php
    hostname: ogrencibaksana_php
    restart: "no"
    links:
      - cntnr_ogrencibaksana_mysql
      - cntnr_ogrencibaksana_phpmyadmin
      - cntnr_ogrencibaksana_redis
      - cntnr_ogrencibaksana_memcached
    volumes:
      - '../projects:/var/www/html'
      - './php/php.ini:/usr/local/etc/php/php.ini'
    ports:
      - '8841:9000'
  cntnr_ogrencibaksana_mysql:
    image: 'mysql:8.0'
    container_name: ogrencibaksana_mysql
    hostname: ogrencibaksana_mysql
    restart: "no"
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '8842:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  cntnr_ogrencibaksana_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ogrencibaksana_phpmyadmin
    hostname: ogrencibaksana_phpmyadmin
    restart: "no"
    depends_on:
      - cntnr_ogrencibaksana_mysql
    links:
      - cntnr_ogrencibaksana_mysql
    ports:
      - '8843:80'
    environment:
      - PMA_HOST=ogrencibaksana_mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - './phpmyadmin/php.ini:/usr/local/etc/php/php.ini'
  cntnr_ogrencibaksana_redis:
    image: 'redis:latest'
    container_name: ogrencibaksana_redis
    hostname: ogrencibaksana_redis
    restart: "no"
    command:
      - redis-server
      - '--appendonly'
      - 'yes'
    ports:
      - '8844:6379'
    volumes:
      - './redis/data:/data'
  cntnr_ogrencibaksana_memcached:
    image: 'memcached:latest'
    container_name: ogrencibaksana_memcached
    hostname: ogrencibaksana_memcached
    restart: "no"
    ports:
      - '8845:11211'